name: NewsBuzz
description: Daily News

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  share: ^0.6.2+1
  webview_flutter: ^0.3.14+1
  timeago: ^2.0.19
  cupertino_icons: ^0.1.0
  http: ^0.12.0+2
  provider: ^3.1.0
  uuid: ^2.0.2
  encrypt: ^3.3.1
  shared_preferences: ^0.5.3+4
  carousel_slider: ^1.3.1
  auto_size_text: ^2.1.0
  loadmore: ^1.0.4
  flutter_mailer: ^0.4.1+2
  image_picker: ^0.6.1+4
  firebase_messaging: ^5.1.6
  flutter_staggered_grid_view: ^0.3.0
  firebase_storage: ^3.0.6
  html: ^0.14.0+3
  url_launcher: ^5.2.5

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - lang/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/.

  # To add assets from package dependencies, first ensure the asset
  # is in the lib/ directory of the dependency. Then,
  # refer to the asset with a path prefixed with
  # `packages/PACKAGE_NAME/`. The `lib/` is implied, do not
  # include `lib/` in the asset path.
  #
  # Here is an example:
  #
  # assets:
  #  - packages/PACKAGE_NAME/path/to/asset

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
   - family: jazeera
     fonts:
       - asset: fonts/jazeera-Regular.ttf
       - asset: fonts/jazeera-light.ttf
         weight: 200
       - asset: fonts/jazeera-bold.ttf
         weight: 700

